In [4]:
import os
import re
import pandas as pd


filename='kosarak.dat'
path="..\\dataset\\"
src_data=os.path.join(filepath,filename)

itemdict={}
num_line=0
with open(src_data,'r') as file:
    while True:
        e=file.readline().strip('\n')
        if not e:
            break
        else:
            num_line+=1
            if e not in itemdict:
                itemdict[e]=1
            else:
                itemdict[e]+=1
print(num_line)
print(len(itemdict))

df=pd.DataFrame(list(itemdict.items()),columns=['Element', 'Count'])
df=df.reset_index(drop=True)
df=df.sort_values('Count',ascending=False)

groundtruth='kosarak_ground_truth.csv'
df.to_csv(groundtruth,index=False)

xdf=pd.read_csv(groundtruth)
xdf.head(10)

990002
606770

  Element  Count
0       3  36133
1       6  30225
2     6 3  21139
3    11 6  12769
4       1   9766
5  11 6 3   9083
6     1 3   6002
7      11   5374
8     1 6   5046
9       4   4290